name: Create Release with Extension ZIP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Create Extension ZIP
        run: |
          cd chatgpt-overlay
          zip -r ../brainrot-stimulation-extension.zip . -x "*.git*"
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.sha.outputs.sha }}
          name: Release ${{ steps.sha.outputs.sha }}
          files: brainrot-stimulation-extension.zip
          generate_release_notes: true
